name: githubmate
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.1.0
  hive: ^2.2.3
  hooks_riverpod: ^1.0.3
  json_annotation: ^4.6.0
  material_design_icons_flutter: ^5.0.6996
  oauth2: ^2.0.0
  riverpod: ^1.0.3
  webview_flutter: ^3.0.0

dev_dependencies:
  auto_route_generator: ^5.0.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
